required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "github.com/kubernetes-sigs/kubebuilder", # For tests
    "k8s.io/client-go/plugin/pkg/client/auth", # for development against real clusters
    "k8s.io/code-generator/cmd/client-gen", # for go generate
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
    ]

[prune]
  go-tests = true


# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"

[[override]]
name = "github.com/golang/protobuf"
version="v1.3.0"


# Overridefor kubernetes dependencies to pin them to a particular version
[[override]]
name="k8s.io/api"
version="kubernetes-1.14.4"

[[override]]
name="k8s.io/apiextensions-apiserver"
version="kubernetes-1.14.4"

[[override]]
name="k8s.io/apimachinery"
version="kubernetes-1.14.4"

[[override]]
name="k8s.io/client-go"
version="kubernetes-1.14.4"

[[override]]
name="k8s.io/kube-aggregator"
version="kubernetes-1.14.4"

[[override]]
name="k8s.io/code-generator"
version="kubernetes-1.14.4"

[[override]]
name="k8s.io/gengo"
revision="0689ccc1d7d65d9dd1bedcc3b0b1ed7df91ba266"

[[override]]
name="sigs.k8s.io/controller-runtime"
# version="v0.2.0-beta.4"
version="v0.2.2"

[[override]]
name="sigs.k8s.io/controller-tools"
version="v0.1.10"

[[override]]
name="sigs.k8s.io/testing_frameworks"
version="v0.1.1"
