apiVersion: v2
name: wave
description: wave chart that runs on kubernetes
version: 4.0.0
appVersion: v0.7.0
keywords:
  - wave
  - kubernetes
home: https://github.com/wave-k8s/wave
sources:
- https://github.com/wave-k8s/wave
