apiVersion: v1
name: wave
description: wave chart that runs on kubernetes
version: 2.0.0
appVersion: v0.5.0
keywords:
  - wave
  - kubernetes
home: https://github.com/wave-k8s/wave
sources:
- https://github.com/wave-k8s/wave
